# Generated by Django 5.1.2 on 2024-12-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_softwaredevelopers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwaredevelopers',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
